export interface SurahItem {
  nomor: number;
  nama: string;
  namaArab: string;
  arti: string;
  jumlahAyat: number;
  juzAwal: number;
  tempatTurun: "Makkiyyah" | "Madaniyyah";
}

export const QURAN_SURAHS: SurahItem[] = [
  { nomor: 1, nama: "Al-Fatihah", namaArab: "الفاتحة", arti: "Pembukaan", jumlahAyat: 7, juzAwal: 1, tempatTurun: "Makkiyyah" },
  { nomor: 2, nama: "Al-Baqarah", namaArab: "البقرة", arti: "Sapi Betina", jumlahAyat: 286, juzAwal: 1, tempatTurun: "Madaniyyah" },
  { nomor: 3, nama: "Ali 'Imran", namaArab: "آل عمران", arti: "Keluarga Imran", jumlahAyat: 200, juzAwal: 3, tempatTurun: "Madaniyyah" },
  { nomor: 4, nama: "An-Nisa'", namaArab: "النساء", arti: "Wanita", jumlahAyat: 176, juzAwal: 4, tempatTurun: "Madaniyyah" },
  { nomor: 5, nama: "Al-Ma'idah", namaArab: "المائدة", arti: "Hidangan", jumlahAyat: 120, juzAwal: 6, tempatTurun: "Madaniyyah" },
  { nomor: 6, nama: "Al-An'am", namaArab: "الأنعام", arti: "Binatang Ternak", jumlahAyat: 165, juzAwal: 7, tempatTurun: "Makkiyyah" },
  { nomor: 7, nama: "Al-A'raf", namaArab: "الأعراف", arti: "Tempat Tertinggi", jumlahAyat: 206, juzAwal: 8, tempatTurun: "Makkiyyah" },
  { nomor: 8, nama: "Al-Anfal", namaArab: "الأنفال", arti: "Rampasan Perang", jumlahAyat: 75, juzAwal: 9, tempatTurun: "Madaniyyah" },
  { nomor: 9, nama: "At-Taubah", namaArab: "التوبة", arti: "Pengampunan", jumlahAyat: 129, juzAwal: 10, tempatTurun: "Madaniyyah" },
  { nomor: 10, nama: "Yunus", namaArab: "يونس", arti: "Nabi Yunus", jumlahAyat: 109, juzAwal: 11, tempatTurun: "Makkiyyah" },
  { nomor: 11, nama: "Hud", namaArab: "هود", arti: "Nabi Hud", jumlahAyat: 123, juzAwal: 11, tempatTurun: "Makkiyyah" },
  { nomor: 12, nama: "Yusuf", namaArab: "يوسف", arti: "Nabi Yusuf", jumlahAyat: 111, juzAwal: 12, tempatTurun: "Makkiyyah" },
  { nomor: 13, nama: "Ar-Ra'd", namaArab: "الرعد", arti: "Guruh", jumlahAyat: 43, juzAwal: 13, tempatTurun: "Madaniyyah" },
  { nomor: 14, nama: "Ibrahim", namaArab: "إبراهيم", arti: "Nabi Ibrahim", jumlahAyat: 52, juzAwal: 13, tempatTurun: "Makkiyyah" },
  { nomor: 15, nama: "Al-Hijr", namaArab: "الحجر", arti: "Gunung Al-Hijr", jumlahAyat: 99, juzAwal: 14, tempatTurun: "Makkiyyah" },
  { nomor: 16, nama: "An-Nahl", namaArab: "النحل", arti: "Lebah", jumlahAyat: 128, juzAwal: 14, tempatTurun: "Makkiyyah" },
  { nomor: 17, nama: "Al-Isra'", namaArab: "الإسراء", arti: "Perjalanan Malam", jumlahAyat: 111, juzAwal: 15, tempatTurun: "Makkiyyah" },
  { nomor: 18, nama: "Al-Kahf", namaArab: "الكهف", arti: "Gua", jumlahAyat: 110, juzAwal: 15, tempatTurun: "Makkiyyah" },
  { nomor: 19, nama: "Maryam", namaArab: "مريم", arti: "Siti Maryam", jumlahAyat: 98, juzAwal: 16, tempatTurun: "Makkiyyah" },
  { nomor: 20, nama: "Taha", namaArab: "طه", arti: "Taha", jumlahAyat: 135, juzAwal: 16, tempatTurun: "Makkiyyah" },
  { nomor: 21, nama: "Al-Anbiya'", namaArab: "الأنبياء", arti: "Para Nabi", jumlahAyat: 112, juzAwal: 17, tempatTurun: "Makkiyyah" },
  { nomor: 22, nama: "Al-Hajj", namaArab: "الحج", arti: "Haji", jumlahAyat: 78, juzAwal: 17, tempatTurun: "Madaniyyah" },
  { nomor: 23, nama: "Al-Mu'minun", namaArab: "المؤمنون", arti: "Orang-orang Mukmin", jumlahAyat: 118, juzAwal: 18, tempatTurun: "Makkiyyah" },
  { nomor: 24, nama: "An-Nur", namaArab: "النور", arti: "Cahaya", jumlahAyat: 64, juzAwal: 18, tempatTurun: "Madaniyyah" },
  { nomor: 25, nama: "Al-Furqan", namaArab: "الفرقان", arti: "Pembeda", jumlahAyat: 77, juzAwal: 18, tempatTurun: "Makkiyyah" },
  { nomor: 26, nama: "Asy-Syu'ara'", namaArab: "الشعراء", arti: "Para Penyair", jumlahAyat: 227, juzAwal: 19, tempatTurun: "Makkiyyah" },
  { nomor: 27, nama: "An-Naml", namaArab: "النمل", arti: "Semut", jumlahAyat: 93, juzAwal: 19, tempatTurun: "Makkiyyah" },
  { nomor: 28, nama: "Al-Qashash", namaArab: "القصص", arti: "Kisah-kisah", jumlahAyat: 88, juzAwal: 20, tempatTurun: "Makkiyyah" },
  { nomor: 29, nama: "Al-'Ankabut", namaArab: "العنكبوت", arti: "Laba-laba", jumlahAyat: 69, juzAwal: 20, tempatTurun: "Makkiyyah" },
  { nomor: 30, nama: "Ar-Rum", namaArab: "الروم", arti: "Bangsa Romawi", jumlahAyat: 60, juzAwal: 21, tempatTurun: "Makkiyyah" },
  { nomor: 31, nama: "Luqman", namaArab: "لقمان", arti: "Keluarga Luqman", jumlahAyat: 34, juzAwal: 21, tempatTurun: "Makkiyyah" },
  { nomor: 32, nama: "As-Sajdah", namaArab: "السجدة", arti: "Sujud", jumlahAyat: 30, juzAwal: 21, tempatTurun: "Makkiyyah" },
  { nomor: 33, nama: "Al-Ahzab", namaArab: "الأحزاب", arti: "Golongan yang Bersekutu", jumlahAyat: 73, juzAwal: 21, tempatTurun: "Madaniyyah" },
  { nomor: 34, nama: "Saba'", namaArab: "سبأ", arti: "Kaum Saba'", jumlahAyat: 54, juzAwal: 22, tempatTurun: "Makkiyyah" },
  { nomor: 35, nama: "Fathir", namaArab: "فاطر", arti: "Pencipta", jumlahAyat: 45, juzAwal: 22, tempatTurun: "Makkiyyah" },
  { nomor: 36, nama: "Ya Sin", namaArab: "يس", arti: "Ya Sin", jumlahAyat: 83, juzAwal: 22, tempatTurun: "Makkiyyah" },
  { nomor: 37, nama: "Ash-Shaffat", namaArab: "الصافات", arti: "Barisan-barisan", jumlahAyat: 182, juzAwal: 23, tempatTurun: "Makkiyyah" },
  { nomor: 38, nama: "Shad", namaArab: "ص", arti: "Shad", jumlahAyat: 88, juzAwal: 23, tempatTurun: "Makkiyyah" },
  { nomor: 39, nama: "Az-Zumar", namaArab: "الزمر", arti: "Rombongan", jumlahAyat: 75, juzAwal: 23, tempatTurun: "Makkiyyah" },
  { nomor: 40, nama: "Ghafir", namaArab: "غافر", arti: "Yang Maha Pengampun", jumlahAyat: 85, juzAwal: 24, tempatTurun: "Makkiyyah" },
  { nomor: 41, nama: "Fushshilat", namaArab: "فصلت", arti: "Yang Dijelaskan", jumlahAyat: 54, juzAwal: 24, tempatTurun: "Makkiyyah" },
  { nomor: 42, nama: "Asy-Syura", namaArab: "الشورى", arti: "Musyawarah", jumlahAyat: 53, juzAwal: 25, tempatTurun: "Makkiyyah" },
  { nomor: 43, nama: "Az-Zukhruf", namaArab: "الزخرف", arti: "Perhiasan", jumlahAyat: 89, juzAwal: 25, tempatTurun: "Makkiyyah" },
  { nomor: 44, nama: "Ad-Dukhan", namaArab: "الدخان", arti: "Kabut", jumlahAyat: 59, juzAwal: 25, tempatTurun: "Makkiyyah" },
  { nomor: 45, nama: "Al-Jatsiyah", namaArab: "الجاثية", arti: "Yang Berlutut", jumlahAyat: 37, juzAwal: 25, tempatTurun: "Makkiyyah" },
  { nomor: 46, nama: "Al-Ahqaf", namaArab: "الأحقاف", arti: "Bukit-bukit Pasir", jumlahAyat: 35, juzAwal: 26, tempatTurun: "Makkiyyah" },
  { nomor: 47, nama: "Muhammad", namaArab: "محمد", arti: "Nabi Muhammad", jumlahAyat: 38, juzAwal: 26, tempatTurun: "Madaniyyah" },
  { nomor: 48, nama: "Al-Fath", namaArab: "الفتح", arti: "Kemenangan", jumlahAyat: 29, juzAwal: 26, tempatTurun: "Madaniyyah" },
  { nomor: 49, nama: "Al-Hujurat", namaArab: "الحجرات", arti: "Kamar-kamar", jumlahAyat: 18, juzAwal: 26, tempatTurun: "Madaniyyah" },
  { nomor: 50, nama: "Qaf", namaArab: "ق", arti: "Qaf", jumlahAyat: 45, juzAwal: 26, tempatTurun: "Makkiyyah" },
  { nomor: 51, nama: "Adz-Dzariyat", namaArab: "الذاريات", arti: "Angin yang Menerbangkan", jumlahAyat: 60, juzAwal: 26, tempatTurun: "Makkiyyah" },
  { nomor: 52, nama: "Ath-Thur", namaArab: "الطور", arti: "Bukit Tursina", jumlahAyat: 49, juzAwal: 27, tempatTurun: "Makkiyyah" },
  { nomor: 53, nama: "An-Najm", namaArab: "النجم", arti: "Bintang", jumlahAyat: 62, juzAwal: 27, tempatTurun: "Makkiyyah" },
  { nomor: 54, nama: "Al-Qamar", namaArab: "القمر", arti: "Bulan", jumlahAyat: 55, juzAwal: 27, tempatTurun: "Makkiyyah" },
  { nomor: 55, nama: "Ar-Rahman", namaArab: "الرحمن", arti: "Yang Maha Pemurah", jumlahAyat: 78, juzAwal: 27, tempatTurun: "Madaniyyah" },
  { nomor: 56, nama: "Al-Waqi'ah", namaArab: "الواقعة", arti: "Hari Kiamat", jumlahAyat: 96, juzAwal: 27, tempatTurun: "Makkiyyah" },
  { nomor: 57, nama: "Al-Hadid", namaArab: "الحديد", arti: "Besi", jumlahAyat: 29, juzAwal: 27, tempatTurun: "Madaniyyah" },
  { nomor: 58, nama: "Al-Mujadilah", namaArab: "المجادلة", arti: "Gugatan", jumlahAyat: 22, juzAwal: 28, tempatTurun: "Madaniyyah" },
  { nomor: 59, nama: "Al-Hasyr", namaArab: "الحشر", arti: "Pengusiran", jumlahAyat: 24, juzAwal: 28, tempatTurun: "Madaniyyah" },
  { nomor: 60, nama: "Al-Mumtahanah", namaArab: "الممتحنة", arti: "Wanita yang Diuji", jumlahAyat: 13, juzAwal: 28, tempatTurun: "Madaniyyah" },
  { nomor: 61, nama: "Ash-Shaff", namaArab: "الصف", arti: "Barisan", jumlahAyat: 14, juzAwal: 28, tempatTurun: "Madaniyyah" },
  { nomor: 62, nama: "Al-Jumu'ah", namaArab: "الجمعة", arti: "Hari Jum'at", jumlahAyat: 11, juzAwal: 28, tempatTurun: "Madaniyyah" },
  { nomor: 63, nama: "Al-Munafiqun", namaArab: "المنافقون", arti: "Orang Munafik", jumlahAyat: 11, juzAwal: 28, tempatTurun: "Madaniyyah" },
  { nomor: 64, nama: "At-Taghabun", namaArab: "التغابن", arti: "Hari Ditampakkan Kesalahan", jumlahAyat: 18, juzAwal: 28, tempatTurun: "Madaniyyah" },
  { nomor: 65, nama: "Ath-Thalaq", namaArab: "الطلاق", arti: "Talak / Perceraian", jumlahAyat: 12, juzAwal: 28, tempatTurun: "Madaniyyah" },
  { nomor: 66, nama: "At-Tahrim", namaArab: "التحريم", arti: "Mengharamkan", jumlahAyat: 12, juzAwal: 28, tempatTurun: "Madaniyyah" },
  { nomor: 67, nama: "Al-Mulk", namaArab: "الملك", arti: "Kerajaan", jumlahAyat: 30, juzAwal: 29, tempatTurun: "Makkiyyah" },
  { nomor: 68, nama: "Al-Qalam", namaArab: "القلم", arti: "Pena", jumlahAyat: 52, juzAwal: 29, tempatTurun: "Makkiyyah" },
  { nomor: 69, nama: "Al-Haqqah", namaArab: "الحاقة", arti: "Hari Kiamat", jumlahAyat: 52, juzAwal: 29, tempatTurun: "Makkiyyah" },
  { nomor: 70, nama: "Al-Ma'arij", namaArab: "المعارج", arti: "Tempat Naik", jumlahAyat: 44, juzAwal: 29, tempatTurun: "Makkiyyah" },
  { nomor: 71, nama: "Nuh", namaArab: "نوح", arti: "Nabi Nuh", jumlahAyat: 28, juzAwal: 29, tempatTurun: "Makkiyyah" },
  { nomor: 72, nama: "Al-Jinn", namaArab: "الجن", arti: "Jin", jumlahAyat: 28, juzAwal: 29, tempatTurun: "Makkiyyah" },
  { nomor: 73, nama: "Al-Muzzammil", namaArab: "المزمل", arti: "Orang yang Berselimut", jumlahAyat: 20, juzAwal: 29, tempatTurun: "Makkiyyah" },
  { nomor: 74, nama: "Al-Muddatstsir", namaArab: "المدثر", arti: "Orang yang Berkemul", jumlahAyat: 56, juzAwal: 29, tempatTurun: "Makkiyyah" },
  { nomor: 75, nama: "Al-Qiyamah", namaArab: "القيامة", arti: "Hari Kiamat", jumlahAyat: 40, juzAwal: 29, tempatTurun: "Makkiyyah" },
  { nomor: 76, nama: "Al-Insan", namaArab: "الإنسان", arti: "Manusia", jumlahAyat: 31, juzAwal: 29, tempatTurun: "Madaniyyah" },
  { nomor: 77, nama: "Al-Mursalat", namaArab: "المرسلات", arti: "Malaikat yang Diutus", jumlahAyat: 50, juzAwal: 29, tempatTurun: "Makkiyyah" },
  { nomor: 78, nama: "An-Naba'", namaArab: "النبأ", arti: "Berita Besar", jumlahAyat: 40, juzAwal: 30, tempatTurun: "Makkiyyah" },
  { nomor: 79, nama: "An-Nazi'at", namaArab: "النازعات", arti: "Malaikat yang Mencabut", jumlahAyat: 46, juzAwal: 30, tempatTurun: "Makkiyyah" },
  { nomor: 80, nama: "'Abasa", namaArab: "عبس", arti: "Ia Bermuka Masam", jumlahAyat: 42, juzAwal: 30, tempatTurun: "Makkiyyah" },
  { nomor: 81, nama: "At-Takwir", namaArab: "التكوير", arti: "Menggulung", jumlahAyat: 29, juzAwal: 30, tempatTurun: "Makkiyyah" },
  { nomor: 82, nama: "Al-Infithar", namaArab: "الانفطار", arti: "Terbelah", jumlahAyat: 19, juzAwal: 30, tempatTurun: "Makkiyyah" },
  { nomor: 83, nama: "Al-Muthaffifin", namaArab: "المطففين", arti: "Orang-orang Curang", jumlahAyat: 36, juzAwal: 30, tempatTurun: "Makkiyyah" },
  { nomor: 84, nama: "Al-Insyiqaq", namaArab: "الانشقاق", arti: "Terbelah", jumlahAyat: 25, juzAwal: 30, tempatTurun: "Makkiyyah" },
  { nomor: 85, nama: "Al-Buruj", namaArab: "البروج", arti: "Gugusan Bintang", jumlahAyat: 22, juzAwal: 30, tempatTurun: "Makkiyyah" },
  { nomor: 86, nama: "Ath-Thariq", namaArab: "الطارق", arti: "Yang Datang di Malam Hari", jumlahAyat: 17, juzAwal: 30, tempatTurun: "Makkiyyah" },
  { nomor: 87, nama: "Al-A'la", namaArab: "الأعلى", arti: "Yang Paling Tinggi", jumlahAyat: 19, juzAwal: 30, tempatTurun: "Makkiyyah" },
  { nomor: 88, nama: "Al-Ghasyiyah", namaArab: "الغاشية", arti: "Hari Pembalasan", jumlahAyat: 26, juzAwal: 30, tempatTurun: "Makkiyyah" },
  { nomor: 89, nama: "Al-Fajr", namaArab: "الفجر", arti: "Fajar", jumlahAyat: 30, juzAwal: 30, tempatTurun: "Makkiyyah" },
  { nomor: 90, nama: "Al-Balad", namaArab: "البلد", arti: "Negeri", jumlahAyat: 20, juzAwal: 30, tempatTurun: "Makkiyyah" },
  { nomor: 91, nama: "Asy-Syams", namaArab: "الشمس", arti: "Matahari", jumlahAyat: 15, juzAwal: 30, tempatTurun: "Makkiyyah" },
  { nomor: 92, nama: "Al-Lail", namaArab: "الليل", arti: "Malam", jumlahAyat: 21, juzAwal: 30, tempatTurun: "Makkiyyah" },
  { nomor: 93, nama: "Adh-Dhuha", namaArab: "الضحى", arti: "Waktu Dhuha", jumlahAyat: 11, juzAwal: 30, tempatTurun: "Makkiyyah" },
  { nomor: 94, nama: "Al-Insyirah", namaArab: "الشرح", arti: "Kelapangan", jumlahAyat: 8, juzAwal: 30, tempatTurun: "Makkiyyah" },
  { nomor: 95, nama: "At-Tin", namaArab: "التين", arti: "Buah Tin", jumlahAyat: 8, juzAwal: 30, tempatTurun: "Makkiyyah" },
  { nomor: 96, nama: "Al-'Alaq", namaArab: "العلق", arti: "Segumpal Darah", jumlahAyat: 19, juzAwal: 30, tempatTurun: "Makkiyyah" },
  { nomor: 97, nama: "Al-Qadr", namaArab: "القدر", arti: "Kemuliaan", jumlahAyat: 5, juzAwal: 30, tempatTurun: "Makkiyyah" },
  { nomor: 98, nama: "Al-Bayyinah", namaArab: "البينة", arti: "Bukti Nyata", jumlahAyat: 8, juzAwal: 30, tempatTurun: "Madaniyyah" },
  { nomor: 99, nama: "Az-Zalzalah", namaArab: "الزلزلة", arti: "Keguncangan", jumlahAyat: 8, juzAwal: 30, tempatTurun: "Madaniyyah" },
  { nomor: 100, nama: "Al-'Adiyat", namaArab: "العاديات", arti: "Kuda Perang", jumlahAyat: 11, juzAwal: 30, tempatTurun: "Makkiyyah" },
  { nomor: 101, nama: "Al-Qari'ah", namaArab: "القارعة", arti: "Hari Kiamat", jumlahAyat: 11, juzAwal: 30, tempatTurun: "Makkiyyah" },
  { nomor: 102, nama: "At-Takatsur", namaArab: "التكاثر", arti: "Bermegah-megahan", jumlahAyat: 8, juzAwal: 30, tempatTurun: "Makkiyyah" },
  { nomor: 103, nama: "Al-'Ashr", namaArab: "العصر", arti: "Masa / Waktu", jumlahAyat: 3, juzAwal: 30, tempatTurun: "Makkiyyah" },
  { nomor: 104, nama: "Al-Humazah", namaArab: "الهمزة", arti: "Pengumpat", jumlahAyat: 9, juzAwal: 30, tempatTurun: "Makkiyyah" },
  { nomor: 105, nama: "Al-Fil", namaArab: "الفيل", arti: "Gajah", jumlahAyat: 5, juzAwal: 30, tempatTurun: "Makkiyyah" },
  { nomor: 106, nama: "Quraisy", namaArab: "قريش", arti: "Suku Quraisy", jumlahAyat: 4, juzAwal: 30, tempatTurun: "Makkiyyah" },
  { nomor: 107, nama: "Al-Ma'un", namaArab: "الماعون", arti: "Barang-barang Berguna", jumlahAyat: 7, juzAwal: 30, tempatTurun: "Makkiyyah" },
  { nomor: 108, nama: "Al-Kautsar", namaArab: "الكوثر", arti: "Nikmat yang Banyak", jumlahAyat: 3, juzAwal: 30, tempatTurun: "Makkiyyah" },
  { nomor: 109, nama: "Al-Kafirun", namaArab: "الكافرون", arti: "Orang-orang Kafir", jumlahAyat: 6, juzAwal: 30, tempatTurun: "Makkiyyah" },
  { nomor: 110, nama: "An-Nashr", namaArab: "النصر", arti: "Pertolongan", jumlahAyat: 3, juzAwal: 30, tempatTurun: "Madaniyyah" },
  { nomor: 111, nama: "Al-Lahab", namaArab: "اللهب", arti: "Gejolak Api", jumlahAyat: 5, juzAwal: 30, tempatTurun: "Makkiyyah" },
  { nomor: 112, nama: "Al-Ikhlash", namaArab: "الإخلاص", arti: "Kemurnian Keesaan Allah", jumlahAyat: 4, juzAwal: 30, tempatTurun: "Makkiyyah" },
  { nomor: 113, nama: "Al-Falaq", namaArab: "الفلق", arti: "Waktu Shubuh", jumlahAyat: 5, juzAwal: 30, tempatTurun: "Makkiyyah" },
  { nomor: 114, nama: "An-Nas", namaArab: "الناس", arti: "Manusia", jumlahAyat: 6, juzAwal: 30, tempatTurun: "Makkiyyah" },
];

// Helper to determine Juz based on surah number if needed
export function getSurahByNumber(num: number): SurahItem | undefined {
  return QURAN_SURAHS.find((s) => s.nomor === num);
}

// Approximate Juz starting surahs for visual 30 juz map
export const JUZ_INFO = [
  { juz: 1, nama: "Juz 1", surahAwal: "Al-Fatihah 1", surahAkhir: "Al-Baqarah 141" },
  { juz: 2, nama: "Juz 2", surahAwal: "Al-Baqarah 142", surahAkhir: "Al-Baqarah 252" },
  { juz: 3, nama: "Juz 3", surahAwal: "Al-Baqarah 253", surahAkhir: "Ali 'Imran 92" },
  { juz: 4, nama: "Juz 4", surahAwal: "Ali 'Imran 93", surahAkhir: "An-Nisa' 23" },
  { juz: 5, nama: "Juz 5", surahAwal: "An-Nisa' 24", surahAkhir: "An-Nisa' 147" },
  { juz: 6, nama: "Juz 6", surahAwal: "An-Nisa' 148", surahAkhir: "Al-Ma'idah 81" },
  { juz: 7, nama: "Juz 7", surahAwal: "Al-Ma'idah 82", surahAkhir: "Al-An'am 110" },
  { juz: 8, nama: "Juz 8", surahAwal: "Al-An'am 111", surahAkhir: "Al-A'raf 87" },
  { juz: 9, nama: "Juz 9", surahAwal: "Al-A'raf 88", surahAkhir: "Al-Anfal 40" },
  { juz: 10, nama: "Juz 10", surahAwal: "Al-Anfal 41", surahAkhir: "At-Taubah 92" },
  { juz: 11, nama: "Juz 11", surahAwal: "At-Taubah 93", surahAkhir: "Hud 5" },
  { juz: 12, nama: "Juz 12", surahAwal: "Hud 6", surahAkhir: "Yusuf 52" },
  { juz: 13, nama: "Juz 13", surahAwal: "Yusuf 53", surahAkhir: "Ibrahim 52" },
  { juz: 14, nama: "Juz 14", surahAwal: "Al-Hijr 1", surahAkhir: "An-Nahl 128" },
  { juz: 15, nama: "Juz 15", surahAwal: "Al-Isra' 1", surahAkhir: "Al-Kahf 74" },
  { juz: 16, nama: "Juz 16", surahAwal: "Al-Kahf 75", surahAkhir: "Taha 135" },
  { juz: 17, nama: "Juz 17", surahAwal: "Al-Anbiya' 1", surahAkhir: "Al-Hajj 78" },
  { juz: 18, nama: "Juz 18", surahAwal: "Al-Mu'minun 1", surahAkhir: "Al-Furqan 20" },
  { juz: 19, nama: "Juz 19", surahAwal: "Al-Furqan 21", surahAkhir: "An-Naml 55" },
  { juz: 20, nama: "Juz 20", surahAwal: "An-Naml 56", surahAkhir: "Al-'Ankabut 45" },
  { juz: 21, nama: "Juz 21", surahAwal: "Al-'Ankabut 46", surahAkhir: "Al-Ahzab 30" },
  { juz: 22, nama: "Juz 22", surahAwal: "Al-Ahzab 31", surahAkhir: "Ya Sin 27" },
  { juz: 23, nama: "Juz 23", surahAwal: "Ya Sin 28", surahAkhir: "Az-Zumar 31" },
  { juz: 24, nama: "Juz 24", surahAwal: "Az-Zumar 32", surahAkhir: "Fushshilat 46" },
  { juz: 25, nama: "Juz 25", surahAwal: "Fushshilat 47", surahAkhir: "Al-Jatsiyah 37" },
  { juz: 26, nama: "Juz 26", surahAwal: "Al-Ahqaf 1", surahAkhir: "Adz-Dzariyat 30" },
  { juz: 27, nama: "Juz 27", surahAwal: "Adz-Dzariyat 31", surahAkhir: "Al-Hadid 29" },
  { juz: 28, nama: "Juz 28", surahAwal: "Al-Mujadilah 1", surahAkhir: "At-Tahrim 12" },
  { juz: 29, nama: "Juz 29", surahAwal: "Al-Mulk 1", surahAkhir: "Al-Mursalat 50" },
  { juz: 30, nama: "Juz 30 (Juz 'Amma)", surahAwal: "An-Naba' 1", surahAkhir: "An-Nas 6" },
];
